// Generated by https://quicktype.io

export interface OptionCategoriesInterface {
    SDTCategorias: SDTCategoria[];
}

export interface SDTCategoria {
    Id:     string;
    Desc:   string;
    Level2: Level2[];
}

export interface Level2 {
    Id:   string;
    Desc: string;
}
