// Generated by https://quicktype.io

export interface ListPrefixInterface {
    sdtTitulos: SdtTitulo[];
}

export interface SdtTitulo {
    TituloPersonaId:   string;
    TituloPersonaDesc: string;
}
