// Generated by https://quicktype.io

export interface ListSegmentsInterface {
    ListSegmentos: ListSegmento[];
}

export interface ListSegmento {
    Nivel1Id:    Nivel1ID;
    Nivel1Desc:  Nivel1Desc;
    Nivel2Id:    string;
    Nivel2Desc:  string;
    Nivel3Id:    string;
    Descripcion: string;
}

export enum Nivel1Desc {
    Alimentos = "ALIMENTOS",
    Belleza = "BELLEZA",
    Educacion = "EDUCACION",
    Hogar = "HOGAR",
    Mascotas = "MASCOTAS",
    Salud = "SALUD",
    Servicios = "SERVICIOS",
    Transporte = "TRANSPORTE",
    Turismo = "TURISMO",
    Vestir = "VESTIR",
}

export enum Nivel1ID {
    S01 = "S01",
    S02 = "S02",
    S03 = "S03",
    S04 = "S04",
    S05 = "S05",
    S06 = "S06",
    S07 = "S07",
    S08 = "S08",
    S09 = "S09",
    S10 = "S10",
}
