// Generated by https://quicktype.io

export interface ListColoniesInterface {
    ListColonias: ListColonia[];
}

export interface ListColonia {
    CPID:        string;
    CPColonia:   string;
    CPMunicipio: string;
    CPEstado:    string;
    CPCiudad:    string;
}
